//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Object_Location
    {
        public int Ob_ID { get; set; }
        public int Lo_ID { get; set; }
        public int Qty { get; set; }
    
        public virtual Tbl_Location Tbl_Location { get; set; }
        public virtual Tbl_Object Tbl_Object { get; set; }
    }
}
