//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Object
    {
        public int Ob_ID { get; set; }
        [DisplayName("Category")]
        public int FK_Ca_ID { get; set; }
        [DisplayName("Name")]
        public string Ob_Name { get; set; }
        [DisplayName("Purchase Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> Ob_Purchase_Date { get; set; }
        [DisplayName("Estimated Value")]
        public Nullable<double> Ob_Est_Value { get; set; }
        [DisplayName("Description")]
        public string Ob_Description { get; set; }
        [DisplayName("Quantity")]
        public int Ob_Quantity { get; set; }
        [DisplayName("Location")]
        public Nullable<int> FK_Lo_ID { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
        public virtual Tbl_Location Tbl_Location { get; set; }
    }
}
